<a href="https://colab.research.google.com/github/Deepak-Kambala/Machine-Learning/blob/main/iris_multivariate_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

In [44]:
flower = load_iris()

In [45]:
dir(flower)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [46]:
flower.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [47]:
flower.target[0]

np.int64(0)

In [48]:
flower.target_names[0]

np.str_('setosa')

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test =  train_test_split(flower.data, flower.target, test_size=0.2)

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
model = LogisticRegression()

In [53]:
model.fit(X_train, y_train)

LogisticRegression()

In [54]:
model.score(X_test,y_test)

1.0

In [55]:
flower.data[21]

array([5.1, 3.7, 1.5, 0.4])

In [56]:
flower.target[21]

np.int64(0)

In [57]:
model.predict([[5.1, 3.7, 1.5, 0.4]])

array([0])